server:
  port: 8082

spring:
  main:
    allow-circular-references: true
  application:
    name: chinese-chess
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8888/chess?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&pipeName=MySQL
    username: root
    password: 888888
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chess.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.chess: DEBUG
